Public API Strong Typing for kiwi package_manager
OSInside/kiwi pull request #1762
Opened 2021-03-11 18:25 UTC by KeithMnemonic

Apply Strong Typing to KIWI Public APIs for package_manager files

 package_manager/base.py
 package_manager/pacman.py
 package_manager/microdnf.py
 package_manager/apt.py
 package_manager/dnf.py
 package_manager/zypper.py

This references Issue #1644

2021-03-12 12:17 UTC, schaefi requested changes
Thanks, this is a great start :+1: 

See my comments, mostly nitpick but there is also one inconsistency which I think was handled incorrectly. More details in an extra comment

2021-03-12 12:17 UTC, schaefi commented on kiwi/package_manager/base.py
> +    def post_init(self, custom_args: list = None) -> None:
Should this not also use the List type from Typing ?

2021-03-12 12:17 UTC, schaefi commented on kiwi/package_manager/apt.py
> +
Any reason for the extra empty line ?

2021-03-12 12:17 UTC, schaefi commented on kiwi/package_manager/base.py
> +    def match_package_installed(self, package_list: list, log_line: str) -> Union[Match, None]:
list vs List ?

2021-03-12 12:17 UTC, schaefi commented on kiwi/package_manager/dnf.py
> +    def post_init(self, custom_args: list = None) -> None:
list vs. List

2021-03-12 12:17 UTC, schaefi commented on kiwi/package_manager/dnf.py
> +    def match_package_installed(self, package_list: list, log_line: str) -> Union[Match, None]:
list vs. List

2021-03-12 12:17 UTC, schaefi commented on kiwi/package_manager/dnf.py
> +    def match_package_deleted(self, package_list: list, log_line: str) -> Union[Match, None]:
list vs. List

2021-03-12 12:17 UTC, schaefi commented on kiwi/package_manager/microdnf.py
> +    def post_init(self, custom_args: list = None) -> None:
list vs. List

2021-03-12 12:17 UTC, schaefi commented on kiwi/package_manager/microdnf.py
> +    def match_package_installed(self, package_list: list, log_line: str) -> Union[Match, None]:
list vs. List

2021-03-12 12:17 UTC, schaefi commented on kiwi/package_manager/microdnf.py
> +    def match_package_deleted(self, package_list: list, log_line: str) -> Union[Match, None]:
list vs. List

2021-03-12 12:17 UTC, schaefi commented on kiwi/package_manager/pacman.py
> +    def post_init(self, custom_args: list = None) -> None:
list vs. List

2021-03-12 12:17 UTC, schaefi commented on kiwi/package_manager/pacman.py
> +    def match_package_installed(self, package_list: list, log_line: str) -> Union[Match, None]:
list vs. List

2021-03-12 12:17 UTC, schaefi commented on kiwi/package_manager/pacman.py
> +    def match_package_deleted(self, package_list: list, log_line: str) -> Union[Match, None]:
list vs. List

2021-03-12 12:17 UTC, schaefi commented on kiwi/package_manager/zypper.py
> +    def post_init(self, custom_args: list = None) -> None:
list vs. List

2021-03-12 12:17 UTC, schaefi commented on kiwi/package_manager/zypper.py
> +    def match_package_installed(self, package_list: list, log_line: str) -> Union[Match, None]:
list vs. List

2021-03-12 12:17 UTC, schaefi commented on kiwi/package_manager/zypper.py
> +    def match_package_deleted(self, package_list: list, log_line: str) -> Union[Match, None]:
list vs. List

2021-03-12 12:24 UTC, schaefi commented
@KeithMnemonic I saw you found an inconsistency in the package manager code for the match_package_installed and match_package_deleted functions. Great catch :+1: I however think it was solved in the wrong direction. If you look at ```kiwi/command_process.py``` you see how those methods are called. There is poll_show_progress() which iterates over a list of items (usually package names) and calls for each of them _update_progress(). In that update method you see

```python
match_method(item, command_output)
```

item is always a string and command_output is as well.

Thus the wrong information in the match_package_* methods is the comment block and not the parameters. Therefore I think the type hints should be changed to for example:

```python
def match_package_installed(self, package_name: str, zypper_output: str):
```

and the comment blocks in that functions that tells something about ```:param list package_list: list of all packages``` needs to be fixed, that is a wrong information from my perspective

Thanks much

2021-03-12 20:14 UTC, KeithMnemonic commented
> @KeithMnemonic I saw you found an inconsistency in the package manager code for the match_package_installed and match_package_deleted functions. Great catch 👍 I however think it was solved in the wrong direction. If you look at `kiwi/command_process.py` you see how those methods are called. There is poll_show_progress() which iterates over a list of items (usually package names) and calls for each of them _update_progress(). In that update method you see
> 
> ```python
> match_method(item, command_output)
> ```
> 
> item is always a string and command_output is as well.
> 
> Thus the wrong information in the match_package_* methods is the comment block and not the parameters. Therefore I think the type hints should be changed to for example:
> 
> ```python
> def match_package_installed(self, package_name: str, zypper_output: str):
> ```
> 
> and the comment blocks in that functions that tells something about `:param list package_list: list of all packages` needs to be fixed, that is a wrong information from my perspective
> 
> Thanks much

Markus, I can change it back to package_name and fix the comments block. I am not sure zypper_output will work as it seems the "Codacy" check was complaining and failing about renaming the parameters from the base class base.py and the individual subclasses such as dnf.py,  zypper.py

See this

https://app.codacy.com/gh/OSInside/kiwi/pullRequest?prid=7088745

and let me know how to get around it

2021-03-15 09:25 UTC, schaefi commented
>the "Codacy" check was complaining and failing about renaming the parameters from the base class base.py and the individual subclasses such as dnf.py, zypper.py

yes, it's good that this gets cleaned up now. My suggestion would be. In the base class

```python
def match_package_installed(self, package_name: str, package_manager_output: str) -> bool:
        """
        Match expression to indicate a package has been installed

        Implementation in specialized package manager class

        :param str package_name: unused
        :param str package_manager_output: unused
        """
        raise NotImplementedError
```

and the implementations for the package managers follows this. I'm not sure how mypy reacts on the return statement.
Actually the best solution would be to refactor the base class into a virtual class using ```from abc import ABCMeta, abstractmethod``` But I think this should be an extra pull request as it imho would be too much for the scope of adding type hints in the first place

The other error from codacy ```Method could be a function``` can be solved by using the ```@staticmethod``` decorator

```python
@staticmethod
def has_failed(returncode):
    ...
```

Does this help ?

2021-03-15 13:53 UTC, KeithMnemonic commented
> > the "Codacy" check was complaining and failing about renaming the parameters from the base class base.py and the individual subclasses such as dnf.py, zypper.py
> 
> yes, it's good that this gets cleaned up now. My suggestion would be. In the base class
> 
> ```python
> def match_package_installed(self, package_name: str, package_manager_output: str) -> bool:
>     """
>     Match expression to indicate a package has been installed
> 
>     Implementation in specialized package manager class
> 
>     :param str package_name: unused
>     :param str package_manager_output: unused
>     """
>     raise NotImplementedError
> ```
> 
> and the implementations for the package managers follows this. I'm not sure how mypy reacts on the return statement.
> Actually the best solution would be to refactor the base class into a virtual class using `from abc import ABCMeta, abstractmethod` But I think this should be an extra pull request as it imho would be too much for the scope of adding type hints in the first place
> 
> The other error from codacy `Method could be a function` can be solved by using the `@staticmethod` decorator
> 
> ```python
> @staticmethod
> def has_failed(returncode):
>     ...
> ```
> 
> Does this help ?

Marcus,

from the earlier mypy and codacy failurees, if we are using 

return re.match(
            '.*Unpacking ' + re.escape(package_list) + '.*', log_line
        )

I do  not think ->bool will work in the base class per 

re.match(pattern, string, flags=0)
If zero or more characters at the beginning of string match the regular expression pattern, return a corresponding match object. Return None if the string does not match the pattern; note that this is different from a zero-length match.

that is why I needed the union. Do you want to change all of the subclasses to return True if 'match' and False if 'None'?

2021-03-15 15:22 UTC, schaefi commented
>I do not think ->bool will work in the base class per

>re.match(pattern, string, flags=0)
>If zero or more characters at the beginning of string match the regular expression pattern, return a corresponding match object. >Return None if the string does not match the pattern; note that this is different from a zero-length match.

>that is why I needed the union. Do you want to change all of the subclasses to return True if 'match' and False if 'None'?

I agree with you. I think the code should change to return a bool value. From my perspective the bool operator in python should do the trick

```python
return bool(
    re.match('...', package_manager_output)
)
```

Thanks

2021-03-15 15:24 UTC, KeithMnemonic commented on kiwi/package_manager/apt.py
> +
fixed in latest push

2021-03-15 15:24 UTC, KeithMnemonic commented on kiwi/package_manager/dnf.py
> +    def post_init(self, custom_args: list = None) -> None:
fixed in latest push

2021-03-15 15:24 UTC, KeithMnemonic commented on kiwi/package_manager/pacman.py
> +    def match_package_installed(self, package_list: list, log_line: str) -> Union[Match, None]:
fixed in latest push

2021-03-15 15:24 UTC, KeithMnemonic commented on kiwi/package_manager/zypper.py
> +    def post_init(self, custom_args: list = None) -> None:
fixed in latest push

2021-03-15 15:25 UTC, KeithMnemonic commented on kiwi/package_manager/dnf.py
> +    def match_package_deleted(self, package_list: list, log_line: str) -> Union[Match, None]:
fixed in latest push

2021-03-15 15:25 UTC, KeithMnemonic commented on kiwi/package_manager/microdnf.py
> +    def match_package_installed(self, package_list: list, log_line: str) -> Union[Match, None]:
fixed in latest push

2021-03-15 15:25 UTC, KeithMnemonic commented on kiwi/package_manager/pacman.py
> +    def post_init(self, custom_args: list = None) -> None:
fixed in latest push

2021-03-15 15:25 UTC, KeithMnemonic commented on kiwi/package_manager/microdnf.py
> +    def match_package_deleted(self, package_list: list, log_line: str) -> Union[Match, None]:
fixed in latest push

2021-03-15 15:26 UTC, KeithMnemonic commented on kiwi/package_manager/microdnf.py
> +    def post_init(self, custom_args: list = None) -> None:
fixed in latest push

2021-03-15 17:34 UTC, KeithMnemonic commented
> > I do not think ->bool will work in the base class per
> 
> > re.match(pattern, string, flags=0)
> > If zero or more characters at the beginning of string match the regular expression pattern, return a corresponding match object. >Return None if the string does not match the pattern; note that this is different from a zero-length match.
> 
> > that is why I needed the union. Do you want to change all of the subclasses to return True if 'match' and False if 'None'?
> 
> I agree with you. I think the code should change to return a bool value. From my perspective the bool operator in python should do the trick
> 
> ```python
> return bool(
>     re.match('...', package_manager_output)
> )
> ```
> 
> Thanks

Markus, please re-review and let me know if this looks good now.

2021-03-16 14:22 UTC, schaefi reviewed
That looks very good now

just nitpick on the doc string describing the return and rtype values. I think after you changed that to return bool(...) this information should be adapted in all methods that are affected

2021-03-16 14:22 UTC, schaefi commented on kiwi/package_manager/base.py
> +        :return: Match|None
I think that should be better ```:return: True|False```

2021-03-16 14:22 UTC, schaefi commented on kiwi/package_manager/base.py
> +        :rtype: Match or None
return type is ```:rtype: bool```

2021-03-16 15:03 UTC, KeithMnemonic commented on kiwi/package_manager/base.py
> +        :return: Match|None
please check again with latest push

2021-03-16 15:04 UTC, KeithMnemonic commented on kiwi/package_manager/base.py
> +        :rtype: Match or None
please check again with lastest push

2021-03-17 07:57 UTC, schaefi approved these changes

2021-03-17 07:57 UTC, merged