Add support for riscv64
OSInside/kiwi pull request #1781
Opened 2021-03-29 08:59 UTC by andreas-schwab

2021-03-29 12:39 UTC, Conan-Kudo approved these changes

2021-03-29 12:40 UTC, Conan-Kudo requested changes
Can you add to the unit tests to cover riscv64?

2021-03-29 13:29 UTC, schaefi commented
would be good, something like this

```python
@patch('platform.machine')
def test_post_init_riscv64_platform(self, mock_machine):
    xml_state = MagicMock()
    xml_state.build_type.get_firmware = Mock(
        return_value=None
    )
    mock_machine.return_value = 'riscv64'
    bootloader = BootLoaderConfigGrub2(xml_state, 'root_dir')
    assert bootloader.arch == mock_machine.return_value
```

actually I wonder why there is no coverage complain...

2021-03-30 07:26 UTC, schaefi approved these changes
Looks good to me :+1: Thanks

2021-03-30 10:49 UTC, Conan-Kudo approved these changes

2021-03-30 10:49 UTC, merged