Add more type hints
OSInside/kiwi pull request #2334
Opened 2023-07-24 16:43 UTC by dcermak

Changes proposed in this pull request:
* Add type hints to more modules

2023-07-24 18:32 UTC, dcermak commented
The addition of `TypedDict` adds another requirement for Python <= 3.8: `typing_extensions`. If that is too much, then I can drop that addition as well.

2023-07-25 06:47 UTC, schaefi commented
I like the changes :+1: , not sure about the py >= 3.8 (I think that's what you meant) requirement. For SLE development we need 3.6 and there is a fork of kiwi to maintain kiwi in SLE exactly for reasons like this. Of course it makes maintenance harder. 

I think @Conan-Kudo will object to the change because packaging for Fedora/CentOS/RHEL is based on the pypi upstream tarball and of the python doesn't match they would need to patch out things which is also hard to maintain.

I think we should discuss it either on matrix or in a call

2023-07-25 06:59 UTC, dcermak commented
> not sure about the py >= 3.8 (I think that's what you meant) requirement

You don't need python 3.8 or later. Kiwi still works with 3.6+, but for 3.6 & 3.7 you need the typing_extensions python module as well to import `TypedDict`. I believe it is packaged everywhere, so I don't think it should be a blocker, but it would require updating the spec.

2023-07-31 15:32 UTC, Conan-Kudo requested changes

2023-08-01 06:20 UTC, dcermak commented on .virtualenv.requirements.txt
> +typing_extensions; python_version < '3.8'
Fixed & checked locally that it does the right thing^:tm:

2023-08-01 06:23 UTC, Conan-Kudo submitted a review, later dismissed

2023-08-01 06:27 UTC, dcermak commented on .virtualenv.requirements.txt
> +typing_extensions; python_version < '3.8'
I built the release tarball and pip installed it

2023-08-01 06:59 UTC, Conan-Kudo approved these changes

2023-08-01 06:59 UTC, merged