Add support for BLS zipl
OSInside/kiwi pull request #2500
Opened 2024-03-05 15:22 UTC by schaefi

Add support for

```xml
<bootloader name="zipl" .../>
```

to support BLS based zipl configuration.
This Fixes #2481

2024-03-05 15:24 UTC, schaefi commented
I'm still testing the different boot disks for s390 which will need a bit of time

- [ ] SCSI disk 
- [ ] FBA (byte array) DASD disk
- [ ] DASD 4k block disk

2024-03-08 12:08 UTC, Conan-Kudo commented
Can we make sure we have a test image with Rawhide s390x to validate this?

2024-03-08 15:26 UTC, Conan-Kudo requested changes

2024-03-08 15:26 UTC, Conan-Kudo commented on build-tests/s390/rawhide/test-image-disk/appliance.kiwi
> +    </repository>
This needs to be dropped.

2024-03-10 10:33 UTC, schaefi commented
Ok for me things are working now. Please find the integration tests here:

* https://build.opensuse.org/project/show/Virtualization:Appliances:Images:Testing_s390:rawhide

The Physical profile is for 4k DASD targets whereas the Virtual profile is for zFCP, FBA or virtual (e.g qemu) targets with 512b blocksize

I have tested on s390 itself but also in qemu. If you want to test in qemu please call

```
qemu-system-s390x -m 4096 -nographic -drive if=none,id=dr1,file=kiwi-test-image-disk.s390x-1.42.1-Virtual-Build10.5.qcow2 -device virtio-blk,drive=dr1,bootindex=1
```

Thanks

2024-03-10 11:07 UTC, Conan-Kudo approved these changes

2024-03-10 11:08 UTC, merged