Add schema upgrade opportunity for old schemas
OSInside/kiwi pull request #2523
Opened 2024-04-03 12:12 UTC by schaefi

kiwi files using a schema version < 7.4 are no longer supported by kiwi >= v10.x.x. Thus this commit provides the required XSL stylesheets to upgrade older schemas to v74 such that they can be consumed by the latest kiwi version. The needed xsltproc instruction is placed on the main page of the documentation

2024-04-03 13:31 UTC, Conan-Kudo approved these changes

2024-04-03 13:32 UTC, Conan-Kudo requested changes

2024-04-03 13:32 UTC, Conan-Kudo commented on package/python-kiwi-spec-template
> +%{_usr}/share/kiwi/xsl_to_v74
Please put a trailing slash here.

2024-04-03 14:10 UTC, dcermak reviewed
All these `convertNtoM.xsl` files look autogenerated, wouldn't it make sense to create them here in the repo?

2024-04-03 14:31 UTC, schaefi commented
> All these `convertNtoM.xsl` files look autogenerated, wouldn't it make sense to create them here in the repo?

Oh no they are not auto generated. It was hard manual work to write these style sheets since kiwi exists :) Why do you think that is auto generated code ?

2024-04-03 14:32 UTC, schaefi commented on package/python-kiwi-spec-template
> +%{_usr}/share/kiwi/xsl_to_v74
I will, thanks

2024-04-04 14:35 UTC, schaefi commented on package/python-kiwi-spec-template
> +%{_usr}/share/kiwi/xsl_to_v74
@Conan-Kudo done

2024-04-04 15:12 UTC, Conan-Kudo approved these changes

2024-04-04 15:12 UTC, merged