Fixed ramdisk size setup
OSInside/kiwi pull request #2634
Opened 2024-09-03 07:11 UTC by schaefi

For setting up the brd rd_size option kiwi creates 99-brd.conf used at load time of the kernel brd driver. The location for the conf file is set to /etc/modprobe.d/ However, in newer versions the location has changed to /usr/lib/modprobe.d/ and /etc/modprobe.d no longer exists. This commit allows to handle both systems

2024-09-05 11:18 UTC, Conan-Kudo requested changes
We should *never* create files in `/usr/lib/modprobe.d`. If the directory in `/etc` doesn't exist and we need to put a file there, we need to create the directory.

2024-09-05 11:38 UTC, davidcassany commented
I agree with @Conan-Kudo , creating a file in `/usr/lib/modprobe.d` feels wrong, moreover after some time we (or someone else) are likely to be puzzled by this file not provided by any package and mysteriously added into a sensitive location.
If the path `/etc/modprobe.d` is is still honored I'd say that's the way to go and relay on a `mkdir -p /etc/modprobe.d` or similar approach to ensure the path exists.

2024-09-05 13:52 UTC, schaefi commented
ok, thanks I will do so. Let's hope the /etc location is still honored. Thanks

2024-09-06 06:46 UTC, schaefi commented
@Conan-Kudo @davidcassany ok, I updated the PR, can you take a look again ? Thanks

2024-09-06 06:50 UTC, Conan-Kudo approved these changes

2024-09-06 08:40 UTC, merged